name: Create Release and Package Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write # Erlaubt es dem Workflow, sich selbst abzubrechen

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Read Version from plugin.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' plugin.json)
          echo "version=v$VERSION" >> $GITHUB_OUTPUT

      - name: Check if release already exists
        id: check_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION_TAG="${{ steps.get_version.outputs.version }}"
          if gh release view "$VERSION_TAG" > /dev/null 2>&1; then
            echo "::error::Release $VERSION_TAG already exists! Workflow cancelled. Please adjust the version."
            gh run cancel ${{ github.run_id }}
            sleep 10
            exit 1
          else
            echo "Release $VERSION_TAG does not exist. Continuing..."
          fi

      - name: Read CHANGELOG.md for Release Notes
        id: read_changelog
        run: |
          if [ -f "CHANGELOG.md" ]; then
            echo "body<<{delimiter}" >> $GITHUB_OUTPUT
            cat CHANGELOG.md >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_OUTPUT
            echo "{delimiter}" >> $GITHUB_OUTPUT
          else
            echo "body=Automatically generated release notes for version ${{ steps.get_version.outputs.version }}" >> $GITHUB_OUTPUT
          fi

      - name: Prepare Folder and Filter Files
        run: |
          mkdir mclogcleaner
          shopt -s extglob
          mv !(mclogcleaner|CHANGELOG.md) mclogcleaner/

      - name: Zip the Folder
        run: |
          zip -r mclogcleaner.zip mclogcleaner/

      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          name: "Release ${{ steps.get_version.outputs.version }}"
          body: ${{ steps.read_changelog.outputs.body }}
          files: mclogcleaner.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
